### ISSUE TITLE
May I ask where can I modify the default "sendMessage"？

### ISSUE THREAD

**Issue by Azad-Aihub** [anse-app/chatgpt-demo#388]
### Clear and concise description of the problem

May I ask where can I modify the default "sendMessage"? For example, the original "sendMessage" is "systemMessage: You are ChatGPT, xxxxxxxxxx", and I hope to modify it to my own preset character instead of adding a system role through the page.

### Suggested solution

If possible, perhaps we can add such a code?

`const response = await api.sendMessage(message, {
      ...options,
	systemMessage: `You are ChatGPT, xxxxxxxxxx`,
      onProgress: (partialResponse) => {
        process?.(partialResponse)
      },
    })`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddiu8081** [comment]
Sorry, but I don't quite understand what you mean. 

Whether you were talking about this library [transitive-bullshit/chatgpt-api](https://github.com/transitive-bullshit/chatgpt-api)?
