### ISSUE TITLE
请问怎么替换为azure openai的api key呢？

### ISSUE THREAD

**Issue by mingkwind** [anse-app/chatgpt-demo#399]
我想要把openai的apikey换为使用azure openai的api服务，请问怎么更改呢？

**Comment by yzh990918** [comment]
Sorry, this project only supports configuring openai's apikey.

**Comment by 2432001677** [comment]
> 我想要把openai的apikey换为使用azure openai的api服务，请问怎么更改呢？
You can use my fork: [chatgpt-azure-demo](https://github.com/2432001677/chatgpt-azure-demo)

**Comment by sleepypineapple1** [comment]
> 
I use the fork, but there are still some problem:
<img width="484" alt="屏幕截图 2023-07-13 164103" src="https://github.com/anse-app/chatgpt-demo/assets/139317836/b99ee63c-4136-46bd-b635-3cf092d76a39">

**Comment by 2432001677** [comment]
> > 
> 
> @2432001677 I use the fork, but there are still some problem: <img alt="屏幕截图 2023-07-13 164103" width="484" src="https://user-images.githubusercontent.com/139317836/253218200-b99ee63c-4136-46bd-b635-3cf092d76a39.png">

I missed put `DEPLOY_NAME`(deployment-id) and `API_VERSION`(api-version) in `.env.example`. You can sync my new [commit](https://github.com/anse-app/chatgpt-demo/commit/6f4e4d74ab6a2caca2ce0fdd332ab84cff419cc1).
Read this doc If you don't know where to find them: https://learn.microsoft.com/en-us/azure/cognitive-services/openai/reference#completions

**Comment by sleepypineapple1** [comment]
> > > 
> > 
> > 
> > @2432001677 I use the fork, but there are still some problem: <img alt="屏幕截图 2023-07-13 164103" width="484" src="https://user-images.githubusercontent.com/139317836/253218200-b99ee63c-4136-46bd-b635-3cf092d76a39.png">
> 
> I missed put `DEPLOY_NAME`(deployment-id) and `API_VERSION`(api-version) in `.env.example`. You can sync my new [commit](https://github.com/anse-app/chatgpt-demo/commit/6f4e4d74ab6a2caca2ce0fdd332ab84cff419cc1). Read this doc If you don't know where to find them: https://learn.microsoft.com/en-us/azure/cognitive-services/openai/reference#completions

Thanks, the program ran successfully.
