### ISSUE TITLE
请问部署到netlify是怎么支持流式的

### ISSUE THREAD

**Issue by zzy-life** [anse-app/chatgpt-demo#404]
我谷歌搜索了一下，都是说不支持SSE

**Comment by yzh990918** [comment]
refer: https://docs.netlify.com/edge-functions/api/#web-apis

**Comment by zzy-life** [comment]
我试了一下这个https://github.com/ascorbic/sse-demo/blob/main/netlify/edge-functions/sse.ts
然后一直在循环
这种方法有用吗
