### ISSUE TITLE
提示：invalid_api_key

### ISSUE THREAD

**Issue by amadoncy** [anse-app/chatgpt-demo#406]
### What operating system are you using?

windows10

### What browser are you using?

Chrome

### Describe the bug

添加了gpt的apikey 提示：invalid_api_key

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ddiu8081** [comment]
Please give more information about deploying. e.g. Which target did you deploy, where did you enter the api-key? 

Then reopen it.
