### ISSUE TITLE
之前的vercel 部署， 现如何升级到最新版本

### ISSUE THREAD

**Issue by sytpb** [anse-app/chatgpt-demo#407]
### Describe the feature

I want to know how to upgrade the version to the latest version in vercel .  Is there some way to re-deploy manually .   I know Render.com have this function if you deployed a service from git repo.

**Comment by yzh990918** [comment]
Refer: https://github.com/anse-app/chatgpt-demo#enable-automatic-updates

**Comment by sytpb** [comment]
thanks ,  how to re-deploy in vercel after sync the repo ?   Deployments -> select Current ->Redeploy  ?
