### ISSUE TITLE
vercel的能修改chtgpt的api吗？

### ISSUE THREAD

**Issue by Eldendt** [anse-app/chatgpt-demo#412]
### Describe the feature

vercel的能修改chtgpt的api吗

### Participation

- [ ] I am willing to submit a pull request for this feature.

**Comment by ddiu8081** [comment]
https://github.com/anse-app/chatgpt-demo#environment-variables

**Comment by Eldendt** [comment]
我这个openai账号的余额用完了，想换一个账号的api要怎么换啊，部署的😘😘😘

**Comment by ddiu8081** [comment]
> 我这个openai账号的余额用完了，想换一个账号的api要怎么换啊，部署的😘😘😘

如果有新的API Key的话，在vercel后台修改环境变量为新的，然后等重新部署。
