### ISSUE TITLE
Error: buildx call failed with: ERROR: denied: permission_denied: write_package

### ISSUE THREAD

**Issue by vaynevayne** [anse-app/chatgpt-demo#415]
### How is Anse deployed?

Node

### Describe the bug

https://github.com/vaynevayne/chatgpt-demo/actions/runs/5233296577/jobs/9448676021#step:5:397

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by yzh990918** [comment]
You need to configure the necessary key parameters：https://github.com/anse-app/chatgpt-demo/blob/main/.github/workflows/build-docker.yml#L22
