### ISSUE TITLE
PWA can work in Netlify deploys

### ISSUE THREAD

**Issue by CNSeniorious000** [anse-app/chatgpt-demo#418]
### How is Anse deployed?

Netlify

## Method 1:

Replace

```js
import netlify from '@astrojs/netlify/edge-functions'
```

by

```js
import netlify from '@astrojs/netlify/functions'
```

and remove netlify disable blocks can make PWA work in Netlify.

## Method 2:

Use [inline-registration](https://vite-pwa-org.netlify.app/guide/register-service-worker.html#inline-registration).

Because netlify requires `registerSW.js` to be a function instead of an edge function, so we must remove it or we have to use non-edge functions.

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by CNSeniorious000** [comment]
I implement *Method 2* in #419 and updated some dependencies by the way.

**Comment by yzh990918** [comment]
Done
